labs/yocto-custom-machine/yocto-custom-machine.tex

Fixes: 6073481a4c4f0812aee13ba1d582a6f2e5e9e25d ("yocto: Update custom machine for -DK1 board")
Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>

yocto: fix device-tree name for stm32mp157a-dk1 board

---

labs/sysdev-toolchain/sysdev-toolchain.tex

The lab text mentions a documentation file that only exists in release
tarballs. Better point to the online manual as the name of the file
changed as well.

Refer to the online manual as crosstool-ng dev version does not ship docs.

---

labs/yocto-first-build/yocto-first-build.tex

There was a left over reference to pyro in the first lab.

Minor fix: Update left over reference to pyro (vs. sumo)

---

labs/sysdev-thirdparty/sysdev-thirdparty.tex
slides/sysdev-embedded-linux/sysdev-embedded-linux.tex

_PATH add new dir to the search path, and _LIBDIR replaces path.
When crosscompiling we should not use any .pc file from the
native system thus we should use PKG_CONFIG_LIBDIR.

use PKG_CONFIG_LIBDIR instead of PKG_CONFIG_PATH

---

README

1. Installed packages as described in README
2. `make all` failed with error:
```
! LaTeX Error: File `ulem.sty' not found.
```
Reproduced on Linux Mint 19.3 (5.4.0-54).
According to [Stack Exchange](https://tex.stackexchange.com/questions/489543/ubuntu-18-04-lts-texlive-2018-latex-error-file-ulem-sty-not-found), the simple solution is to add texlive-plain-generic package to the system.
Signed-off-by: Marek Gawryszewski <marek.gawryszewski@protonmail.com>

Added missing package to README

---

labs/buildroot-basic/buildroot-basic.tex

Text and link should refer to the same kernel version (5.4)

Fix Linux kernel version reference

---

labs/kernel-board-setup/kernel-board-setup.tex

The TFTP directory is by default set to **/srv/tftp** on some (newer) systems. @michaelopdenacker

kernel labs: add 'Setting up the TFTP server' section.

---

slides/sysdev-kernel-building/sysdev-kernel-building.tex

Since all the previous explanations use arm-linux- cross-compiler prefix
let's use it here instead of riscv64-linux- prefix.
Signed-off-by: Giulio Benetti <giulio.benetti@benettiengineering.com>

Kernel compiling: use arm-linux- instead of riscv64-linux- with ccache

---

slides/graphics-hardware/graphics-hardware.tex
slides/graphics-software/graphics-software.tex

This PR corrects two misspellings, and I believe that the resistor-ladder digital-to-VGA schematic is for digital-to-analog conversion, not analog-to-digital.

Typo fixes

---

slides/realtime-linux-benchmarking/realtime-linux-benchmarking.tex

As I could see at the help of `trace-cmd` and the usage, the `<opts>` comes after the `<cmd>`

fix <opts> position on trace-cmd command

---

lab-data/embedded-linux/tinysystem/data/www/cgi-bin/cpuinfo

The cpuinfo cgi-script greps for the 'Processor' string; this does not seem to apply to all architecture (on x86_64 it does not work). Grepping for 'model name' seems to be more portable.
Also, having all CPUs on the same line is a little ugly, with the help of sed we can have a single CPU per line.
It requires to add sed in busybox config.
The initial space added before echoing the result of the pipeline helps in aligning the resulting output.

Tinysystem: cpuinfo more portable and better looking

---

README

Generating the Embedded Linux training materials according to the instructions in the README leads to a ghostscript error.
This is due to ghostscript not being listed in the dependencies to install using APT.
Solution: add ghostscript to the instructions.

Add missing ghostscript dependency

---

labs/yocto-custom-image/yocto-custom-image.tex
slides/yocto-image/yocto-image.tex

Use "machine configuration" instead to avoid being ambiguous.

remove all occurences of "machine recipes"

---

slides/yocto-layer/yocto-layer.tex

GStreamer 1.0 has official support in openembedded-core, meta-gstreamer10 is only used for backports.

yocto-layers: remove meta-gstreamer10 from the examples

---

labs/sysdev-buildroot/sysdev-buildroot.tex

In crosstool-ng 1.26.0, the kernel headers version used can't be higher than Linux 6.4.
Telling Buildroot that the toolchain was built with 6.6 headers will cause it to crash with this error message :
"Incorrect selection of kernel headers: expected 6.6.x, got 6.4.x"

labs: sysdev-buildroot: use Linux 6.4 headers

---

slides/sysdev-kernel-building/sysdev-kernel-building.tex

Sysdev kernel building improvements

---

slides/audio-pipewire/audio-pipewire.tex
slides/kernel-device-model/kernel-device-model.tex

Spelling correct resources

---

slides/kernel-source-code-drivers/kernel-source-code-drivers.tex

kernel-source-code-drivers: add libgpiod for userspace driver

---

slides/kernel-frameworks/kernel-frameworks.tex

Devm considered harmful

---

slides/kernel-frameworks/kernel-frameworks.tex

kernel-frameworks: extend information about device types

---

slides/kernel-driver-development-io-memory/kernel-driver-development-io-memory.tex

Fix struct platform device

---

labs/yocto-advanced-configuration/yocto-advanced-configuration.tex

This fixes a small typo in commit f6c905f4a13e15feae904104504a4c3109a421c0.

labs: yocto: Untar the correct file to the NFS directory

---

lab-data/common/bootloader/beaglebone-black/README.md

Move the instructions from monospace plaintext to Markdown. Nothing major, it only makes the document more readable:
- Web will use a sans-serif font,
- We can link to sections from the table of content,
- We can highlight important parts of the instructions.

Improvements to the BBB bootloader instructions

---

labs/kernel-board-setup/kernel-board-setup.tex

The labs instructions refers a section 2.a from another document whereas it is called 2.i.

labs: kernel-board-setup: fix typo

---

common/printk.tex
common/slide-header.tex
slides/sysdev-kernel-building/sysdev-kernel-building.tex
slides/sysdev-linux-intro-features/sysdev-linux-intro-features.tex

Previously, when building the slides for the "linux-kernel-beagleplay" training, the generic "linux-kernel" content was not included. This was due to slide selection relying on exact string matching.
To fix this, replaced the equality check with a prefix match using `\IfBeginWith` from the `xstring` package. Now, all trainings starting with "linux-kernel" correctly include the common kernel content.

slides: fix slide selection logic based on training type

---

README

Since I spent a couple of minutes to find the required packages for Arch Linux for a proper generation of `full-networking-slides.pdf` (only tested this), I'm sharing it here.

README: Add required packages for ArchLinux

---

slides/debugging-system-wide-profiling/debugging-system-wide-profiling.tex
slides/networking-debugging/networking-debugging.tex
slides/networking-driver-netdev/networking-driver-netdev.tex
slides/networking-driver-overview/networking-driver-overview.tex
slides/networking-driver-phy/networking-driver-phy.tex
slides/networking-driver-switch/networking-driver-switch.tex
slides/networking-filtering/networking-filtering.tex
slides/networking-skb/networking-skb.tex
slides/networking-socket/networking-socket.tex
slides/networking-stack-control/networking-stack-control.tex
slides/networking-stack-netdevice/networking-stack-netdevice.tex
slides/networking-stack-overview/networking-stack-overview.tex
slides/networking-traffic-control/networking-traffic-control.tex

I have read and reviewed the `networking-slides.pdf`. I am sharing the spelling mistakes that I found.
**Warning**: Be aware that I may have introduced errors: For some fixes, I am not 100% confident...
I also have the following remarks:
- p26 Transport Layer -> "Can batch Acknowledgments, supports encryption (i think)" <= Yes? : https://en.wikipedia.org/wiki/QUIC#Characteristics
- p130 struct net_offload -> "L2 and L3 headers are added, and a shorter L4 header" <= Maybe reformulate (I may not understand it)?
- p198 XDP_TX -> I suppose by modifying first the destination IP? => The packet is modified, right? Or there is a special rules in the switch?
- p233 Netdev features -> Maybe talk about "vlan_features"?

slides/networking: Fix various spelling mistakes
